### ISSUE TITLE
Make sure to only run in a virtualenv

### ISSUE THREAD

**Issue by notpushkin** [ParthS007/pip-purge#2]
I think it's better to check twice (programmatically, that is) :P

**Comment by saxbophone** [comment]
What do you mean by check twice? As far as I can tell, there is currently no checking if the virtualenv exists at all currently, unless I am missing something obvious 😎

**Comment by notpushkin** [comment]
@saxbophone The first check is obviously on the user:

```
(venv) ~/dev/myapp $ pip-purge  # OK
~ $ pip-purge                   # NOT OK DON'T DO IT PLEASE
```

**Comment by saxbophone** [comment]
Right ok, sorry that wasn't clear based on the wording.

Is this an issue because running it when there's no virtualenv will cause it to fail? I haven't yet been able to check this but will do so when I get a chance.

**Comment by notpushkin** [comment]
At least on Linux systems, there are a lot of packages installed globally that are used by some system-wide apps (like `python-apt` in Debian- and Ubuntu-based distros). Now, it wouldn't let you uninstall some critical packages like that:
```
$ sudo pip uninstall python-apt
Not uninstalling python-apt at /usr/lib/python2.7/dist-packages, owned by OS
```
But I guess it can break something else, who knows what can happen?

**Comment by saxbophone** [comment]
Ah yes, I follow you. So, running `pip-purge` when not in a virtualenv could uninstall all system wide packages (or at least try to, all it takes is for someone to run it as root).

**Comment by notpushkin** [comment]
I've actually run it as root now. Looks like on recent `pip` it doesn't even perform the "owned by OS
" check, so all of my Python 2 packages are gone.

**Comment by saxbophone** [comment]
Oh no! I wish you luck on the road to Python 2 recovery!

**Comment by izrik** [comment]
I can imagine a scenario where someone did in fact want to clear out global packages. It sounds like a simple warning would be helpful. Something like:

```
~ $ pip-purge
Warning! You are not in a virtualenv. This will purge all system-level packages. Continue? [yN]
```

That would:

1. be explicit
2. prevent most accidents
3. wouldn't completely prevent someone from purging all system-level packages if that was what they actually wanted to do.

**Comment by saxbophone** [comment]
I like this idea @izrik - A flag to confirm this at the command-invocation stage would also be good (like Debian `apt-get`'s `--assume-yes` flag.

**Comment by aitoehigie** [comment]
there is already a PR addressing this issue https://github.com/kennethreitz/pip-purge/pull/4

**Comment by aitoehigie** [comment]
This repo seems abandoned in favor of pipenv. The PR addressing the issue of this thread has been left unattended to.
@kennethreitz

**Comment by kennethreitz** [comment]
github sends me so many notifications, most of them go to spam

**Comment by notpushkin** [comment]
@kennethreitz Can't you just mute threads you aren't interested in?

**Comment by kennethreitz** [comment]
they don't go to spam by choice :)

**Comment by kennethreitz** [comment]
P.S. I accidentally wasn't watching this repository
