### ISSUE TITLE
Do you plan to integrate it into pip directly?

### ISSUE THREAD

**Issue by kimond** [ParthS007/pip-purge#3]

**Comment by GabLeRoux** [comment]
[virtualenvwarpper](http://virtualenvwrapper.readthedocs.io/en/latest/) has [`wipeenv`](http://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html?highlight=wipeenv#wipeenv) as answered here: http://stackoverflow.com/a/39422679/1092815. I tested both `pip-purge` and `wipeenv` and they do pretty much the same, but  `wipeenv` has the advantage of not destroying your system's environment (#2) in case you're not in a virtual env :cake:

**Comment by kimond** [comment]
Perhaps adding a warning message such "Warning you're not in a virtualenv" would help to prevent accidentals purges on the system wide. @GabLeRoux, for example, if I don't want to use virtualenvwrapper on my production but I still want to purge my env at each deploy, pip-purge would be a better candidate because virtualenvwrapper needs more configuration. 

By the way `wipeenv` looks great.

**Comment by aitoehigie** [comment]
This issue has been fixed in the latest version.
If you try to run pip-purge outside a virtualenv, it informs you so you dont get to destroy your systems environment.
